# Numpy Arrays and Basics

In [1]:
import numpy as np

 Create an ndarray by passing a lit to np.array() function:

In [3]:
my_list = [1, 2, 3, 4]  # Define a list

my_array = np.array(my_list)  # Pass the list to np.array()

type(my_array)  # Check the Objects type

numpy.ndarray

To create an array with more than one dimension, pass a nested list to np.array():

In [4]:
second_list = [5, 6, 7, 8]

two_d_array = np.array([my_list, second_list])

print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


An **ndarrray** is defined by the number of **diimension** it has, the size of each dimension and the type of data it holds, check the number and size of dimensions of and ndarray with the shape attribute

In [6]:
two_d_array.shape

(2, 4)

The output above shows that this ndarray is **2-dimensional**, since there are two values listed, and the dimensions have length 2 and 4. check the total size (total number if items) in an array with the size attribute:

In [7]:
two_d_array.size

8

Check the **type** of data in an ndarray with the dtype attribute: 

In [9]:
two_d_array.dtype

dtype('int32')

Numpy has a variety of special array creation functions. some handy array creation functions include

In [10]:
# np.identity() to create a square 2d array with 1's across the diagonal

np.identity(n = 5)   # size of the array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
# np.ones() to create an array filled with ones:
np.ones(shape=two_d_array.shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# np.zeros() to create an array filled with zeros:
np.zeros(shape=two_d_array.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Array Indexing and Slicing

In [13]:
one_d_array = np.array([1, 2, 3, 4, 5, 6])

one_d_array[3]  # get the item at index 3

4

In [14]:
one_d_array[3 : ] # get the slice of index 3 to the end

array([4, 5, 6])

In [15]:
one_d_array[::-1] # slice backwards to reverse the array

array([6, 5, 4, 3, 2, 1])

If an ndarrau=y has more than one dimension, separate indexes for each dimension with a comma

In [16]:
# create a new 2d array
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12])

two_d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [17]:
# Get the element at row index 1, column index 4

two_d_array[1, 4]

11

In [18]:
# Slice elements starting at row 2 and column 5

two_d_array[1:, 4:]

array([[11, 12],
       [17, 18]])

## Reshaping Array

Numpy has variety of built in functions to help you manipulate arrays quickly without having to use complicated indexing operaions.

Reshape an array into a new array with the same databut different structure with <code>np.reshape</code>

In [22]:
np.reshape(two_d_array, newshape=(6,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

Unravel a multi-dimensional into 1 dimension with np.ravel():

In [23]:
np.ravel(two_d_array, order='C') # Use C-Style unraveling (by rows)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

Alternatively, use ndarray.flatten() to faltten a multi-dimensional into 1 and return a copy of the result

In [24]:
two_d_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

Get the transpose of an array with ndarray.T:

In [25]:
two_d_array.T

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

In [26]:
array_to_join = np.array([[10, 20, 30], [40, 50, 60,], [70, 80, 90]])

np.concatenate((two_d_array, array_to_join), axis=1)

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 12, 40, 50, 60],
       [13, 14, 15, 16, 17, 18, 70, 80, 90]])

## Array Math Operations

Creating and manipulating arrays is nice, but the true power of numpy arrays is the ability to perform mathematical operations on many values quickly and easily, Like built in Python Objects, you can use math operators like +, -, / and * perform basic math and operations with ndarrays:

In [28]:
two_d_array + 10     # Add 100 to each element

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28]])

In [29]:
two_d_array - 100 # Subtract 100 from each element

array([[-99, -98, -97, -96, -95, -94],
       [-93, -92, -91, -90, -89, -88],
       [-87, -86, -85, -84, -83, -82]])

In [30]:
two_d_array * 2      # Multiply each element by 2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36]])

In [31]:
two_d_array ** 2     # Square each element by 2

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144],
       [169, 196, 225, 256, 289, 324]])

In [32]:
two_d_array % 2     # Take modulus of each element

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]], dtype=int32)

Beyond operating on each element of an array with a single scalar value, you can also use the basic math operators on two arrays with the same shape. When operating on two arrays, the basic math operator function in an element-wise fashion, returning an array with the same shape as the original

In [33]:
small_array1 = np.array([[1,2], [3, 4]])

small_array1 + small_array1

array([[2, 4],
       [6, 8]])

In [34]:
small_array1 - small_array1

array([[0, 0],
       [0, 0]])

In [35]:
small_array1 * small_array1

array([[ 1,  4],
       [ 9, 16]])

In [37]:
small_array1 ** small_array1

array([[  1,   4],
       [ 27, 256]])

Numpy also offers a variety of **named math functions** for ndarrays. There are too many to cover in detail here, so we'll just look at the selection of some of the most useful ones for *Data Analysis*

In [38]:
# Get the mean of all the elements in an array with np.mean()
np.mean(two_d_array)

9.5

In [39]:
# Provide an axis argument to get the mean across a dimension

np.mean(two_d_array, axis=1)   # Get means of each row

array([ 3.5,  9.5, 15.5])

In [40]:
# Get the standard deviation of all the elements in array with sp.std()
np.std(two_d_array)

5.188127472091127

In [42]:
# Provide an axis argument to get standard deviation across a dimension
np.std(two_d_array, axis=0)  # get the stdev for each column

array([4.89897949, 4.89897949, 4.89897949, 4.89897949, 4.89897949,
       4.89897949])

In [43]:
# Sum the elements of an array an axis with np.sum()
np.sum(two_d_array, axis=1)

array([21, 57, 93])

Take the dot product of two arrays with np.dot(). This function performs an element wise, multiply and then sum for 1-dimensional arrays (vectors) and matrix mutiplication for 2-dimensional arrays 

In [44]:
# Take the vector dot product of row 0 and 1
np.dot(two_d_array[0, 0:], # Slice row 0
      two_d_array[1, 0:]) # Slice row 1


217

In [45]:
# Do a matrix multiply

np.dot(small_array1, small_array1)

array([[ 7, 10],
       [15, 22]])